set_attribute -type boolean [get_pins sdram_DQ_iopad_0/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_1/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_2/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_3/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_4/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_5/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_6/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_7/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_8/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_9/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_10/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_11/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_12/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_13/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_14/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_DQ_iopad_15/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_BWS_iopad_0/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_BWS_iopad_1/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_RW_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_LD_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_CKn_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_CK_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_0/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_1/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_2/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_3/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_4/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_5/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_6/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_7/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_8/PAD] is_pad true
set_attribute -type boolean [get_pins sdram_A_iopad_9/PAD] is_pad true
set_attribute -type boolean [get_pins pm66en_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins preq_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pserr_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pperr_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pstop_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pdevsel_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pirdy_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins ptrdy_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pframe_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pc_be_iopad_0/PAD] is_pad true
set_attribute -type boolean [get_pins pc_be_iopad_1/PAD] is_pad true
set_attribute -type boolean [get_pins pc_be_iopad_2/PAD] is_pad true
set_attribute -type boolean [get_pins pc_be_iopad_3/PAD] is_pad true
set_attribute -type boolean [get_pins ppar_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_0/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_1/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_2/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_3/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_4/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_5/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_6/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_7/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_8/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_9/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_10/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_11/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_12/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_13/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_14/PAD] is_pad true
set_attribute -type boolean [get_pins pad_iopad_15/PAD] is_pad true
set_attribute -type boolean [get_pins pgnt_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pidsel_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins prst_n_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins powersave_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pll_bypass_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins scan_en_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins test_mode_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sdr_clk_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins sys_clk_iopad/PAD] is_pad true
set_attribute -type boolean [get_pins pclk_iopad/PAD] is_pad true
