set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1803.300 -nets VDD -layer METAL2 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 351.250 -nets VDD -layer METAL2 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 351.250 -nets VDD -layer METAL3 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1802.070 -nets VDD -layer METAL3 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1792.650 -nets VSS -layer METAL2 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 361.900 -nets VSS -layer METAL2 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 361.910 -nets VSS -layer METAL3 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1791.410 -nets VSS -layer METAL3 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
create_power_straps  -direction vertical  -start_at 373.330 -nets VDD -layer 26 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 1673.980 -start_high_ends coordinate  -start_high_ends_coordinate 1781.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 577.790 -nets VDD -layer 26 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 1673.980 -start_high_ends coordinate  -start_high_ends_coordinate 1781.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1780.040 -nets VDD -layer 30 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 371.830 -start_high_ends coordinate  -start_high_ends_coordinate 579.290 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1675.480 -nets VDD -layer 30 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 371.830 -start_high_ends coordinate  -start_high_ends_coordinate 579.290 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 369.975 -nets VSS -layer 26 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 1670.380 -start_high_ends coordinate  -start_high_ends_coordinate 1785.140 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 581.145 -nets VSS -layer 26 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 1670.380 -start_high_ends coordinate  -start_high_ends_coordinate 1785.140 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1783.640 -nets VSS -layer 30 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 368.475 -start_high_ends coordinate  -start_high_ends_coordinate 582.645 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1671.880 -nets VSS -layer 30 -width 3.000 -start_low_ends coordinate  -start_low_ends_coordinate 368.475 -start_high_ends coordinate  -start_high_ends_coordinate 582.645 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 497.690 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1394.120 -start_high_ends coordinate  -start_high_ends_coordinate 1676.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 497.690 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1778.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 626.440 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 754.670 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 882.910 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1396.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1011.140 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1422.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1011.140 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1768.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1139.890 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1422.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1139.890 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1768.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1268.130 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1422.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1268.130 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1768.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1396.360 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1422.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1396.360 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1768.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1524.600 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 384.780 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1524.600 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 650.600 -start_high_ends coordinate  -start_high_ends_coordinate 1676.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1524.600 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1778.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1653.350 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 384.780 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1653.350 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 650.600 -start_high_ends coordinate  -start_high_ends_coordinate 1676.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1653.350 -nets VDD  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1778.540 -start_high_ends coordinate  -start_high_ends_coordinate 1807.070 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 501.050 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1397.480 -start_high_ends coordinate  -start_high_ends_coordinate 1673.380 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 501.050 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1782.140 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 629.800 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 758.040 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1012.730 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 886.270 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1400.240 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1014.510 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1418.400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1014.510 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1772.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1143.260 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1418.400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1143.260 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1772.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1271.490 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1418.400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1271.490 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1772.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1399.730 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1418.400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1399.730 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1772.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1527.960 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 381.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1527.960 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 654.280 -start_high_ends coordinate  -start_high_ends_coordinate 1673.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1527.960 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1782.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1656.710 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 381.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1656.710 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 654.280 -start_high_ends coordinate  -start_high_ends_coordinate 1673.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1656.710 -nets VSS  -layer METAL4 -width 2.760 -pitch_within_group 128.360 -start_low_ends coordinate  -start_low_ends_coordinate 1782.220 -start_high_ends coordinate  -start_high_ends_coordinate 1796.410 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 498.020 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 881.530 -start_high_ends coordinate  -start_high_ends_coordinate 1452.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 498.020 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1768.490 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 626.000 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 881.530 -start_high_ends coordinate  -start_high_ends_coordinate 1452.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 626.000 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1768.490 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 753.980 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 881.530 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 882.770 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 881.530 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1010.750 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 384.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1010.750 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 610.230 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1138.730 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 384.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1138.730 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 610.230 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1267.520 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 384.830 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1267.520 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 610.230 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1395.500 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1523.480 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 756.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1523.480 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1429.010 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1652.270 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 756.050 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1652.270 -nets VDD  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1429.010 -start_high_ends coordinate  -start_high_ends_coordinate 1808.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 501.380 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 884.890 -start_high_ends coordinate  -start_high_ends_coordinate 1449.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 501.380 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1771.900 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 629.360 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 884.890 -start_high_ends coordinate  -start_high_ends_coordinate 1449.300 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 629.360 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1771.900 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 757.340 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 884.890 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 886.130 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 884.890 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1014.110 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 381.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1014.110 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 613.640 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1142.090 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 381.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1142.090 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 613.640 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1270.880 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 381.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1270.880 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 613.640 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1398.860 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1526.840 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 759.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1526.840 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1432.420 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1655.630 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 759.420 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1655.630 -nets VSS  -layer METAL5 -width 2.760 -pitch_within_group 128.250 -start_low_ends coordinate  -start_low_ends_coordinate 1432.420 -start_high_ends coordinate  -start_high_ends_coordinate 1797.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
